### ISSUE TITLE
clickhouse support

### ISSUE THREAD

**Issue by Slach** [dqops/dqo#36]
thanks you for your great efforts!

could you implements ClickHouse support for your data quality platform?
ClickHouse is blazing fast columnar database for analytics
look https://clickhouse.com/docs/en/ and https://github.com/ClickHouse/clickhouse-java for details

**Comment by dqops** [comment]
Support for ClickHouse is in the backlog, but so far, not a single potential user has asked for it.
If a paying user is willing to sponsor this feature, we will add it within four weeks.

**Comment by dqops** [comment]
We just added support for ClickHouse in the development version of DQOps. It will be released in the upcoming version.
If you want to test it, you can try it by compiling the code from the "develop" branch.
